### ISSUE TITLE
HomeKit states "Not Supported"

### ISSUE THREAD

**Issue by kobel240** [silviokennecke/homebridge-gpio-doorbell#1]
I added the doorbell to my homebridge and is shows up in my home app but It doesn't ring when I push the button and it shows a not supported message. I also think that homekit thinks that this bell has a camera because it asked for face recognition when setting up... maybe that has something to do with it

**Comment by silviokennecke** [comment]
Yes, the Apple Home App shows that the accessory is not supported. This is because the official HomeKit specification want’s the doorbell service to be exposed by a video doorbell. It should ring anyway.

Could you please provide the following information:
- Enable Debug Mode, Ring the doorbell, send the Logs for that
- To which pins did you connect your doorbell on your pi?
- A scheme how the button is connected to your pi (photo also ok). Is the button directly connected, if not what is in between?
- The installed version of homebridge, NodeJS and the plugin

**Comment by kobel240** [comment]
Ok I managed to ring the bell, the problem was that I used a GPIO button instead of an actual doorbell and so I needed gpio pull down.
But for the "not supported" part? Are you saying that if I add a camera and set it up correctly, I can make it not "not supported"?

**Comment by silviokennecke** [comment]
Yes. For the camera I didn’t want to implement a camera accessory myself. I would recommend using ffmpeg for that. In the [readme](https://github.com/silviokennecke/homebridge-gpio-doorbell#add-to-camera) you find some more instructions. If you don’t have a camera it’s also okay, as you can input a static image to ffmpeg. I hope this helps @kobel240?
